name: flutter_rss_news_reader
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:

  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8

  flutter:
    sdk: flutter

  flutter_inappwebview: ^6.1.5
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  hooks_riverpod: ^2.6.1
  http: ^1.4.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  url_launcher: ^6.3.1
  webview_flutter: ^4.12.0
  xml: ^6.5.0

dev_dependencies:

  build_runner: ^2.4.15
  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:

  uses-material-design: true

flutter_native_splash:
  image: "assets/images/ic_launcher.png"
  color: "212121"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"

  adaptive_icon_background: "#212121"
  adaptive_icon_foreground: "assets/images/ic_launcher.png"
